name       : gnome-clocks
version    : 3.20.2
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-clocks/3.20/gnome-clocks-3.20.2.tar.xz : 7db01207eb9632cec748772b859900313732eacca652753d771fd99a32713617
license    :
    - GPL-2.0
summary    : Gnome Clock application
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gsound)
    - itstool
rundeps    :
    - geoclue
description: |
    World clocks, stopwatch, alarms and more
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
