name       : gnome-clocks
version    : 3.34.0
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-clocks/3.34/gnome-clocks-3.34.0.tar.xz : 61195f357c63b65b75e209494e12a122a802c75333290e136813565dca94f03c
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Clock application
description: |
    World clocks, stopwatch, alarms and more
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsound)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra)
    - itstool
    - vala
rundeps    :
    - geoclue
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
