name       : gnome-clocks
version    : 3.26.0
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-clocks/3.26/gnome-clocks-3.26.0.tar.xz : 0f30a0260e73c8c2925fb24b6abca0ad65f3021d695c42d74ccb2f18225e4501
license    : GPL-2.0
component  : desktop.gnome
summary    : Gnome Clock application
description: |
    World clocks, stopwatch, alarms and more
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsound)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra)
    - itstool
    - vala
rundeps    :
    - geoclue
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
