name       : gnome-clocks
version    : 3.28.0
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-clocks/3.28/gnome-clocks-3.28.0.tar.xz : d48e0bd0479b575adfc7beaa7cd9088258ee27142ab6305915a92cc8761aa7b5
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Clock application
description: |
    World clocks, stopwatch, alarms and more
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsound)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra)
    - itstool
    - vala
rundeps    :
    - geoclue
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
