name       : gnome-clocks
version    : 3.32.0
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-clocks/3.32/gnome-clocks-3.32.0.tar.xz : 6c8d90b0044f535f239bd94a7d0e46d0c9da32a6a141ff1233a78fa99a7cd4f0
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Clock application
description: |
    World clocks, stopwatch, alarms and more
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsound)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra)
    - itstool
    - vala
rundeps    :
    - geoclue
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
