name       : gnome-clocks
version    : 3.22.1
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-clocks/3.22/gnome-clocks-3.22.1.tar.xz : bee05dd8e7b7c79a3ff6d8505c0ecc3bae16002128ec0e2065dd25aa5e5416af
license    : GPL-2.0
component  : desktop.gnome
summary    : Gnome Clock application
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gsound)
    - itstool
rundeps    :
    - geoclue
description: |
    World clocks, stopwatch, alarms and more
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
