name       : gnome-clocks
version    : 3.26.1
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-clocks/3.26/gnome-clocks-3.26.1.tar.xz : 2bd8d8df1d6aa0feddd4afc15d84b1308202fda59a3c3be42e3bce7e9ccd11f7
license    : GPL-2.0
component  : desktop.gnome
summary    : Gnome Clock application
description: |
    World clocks, stopwatch, alarms and more
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsound)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra)
    - itstool
    - vala
rundeps    :
    - geoclue
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
